// tab_2_vue/src/components/Form/Form.vue
<template>
  <Box title="Tabs" className="BoxTabs">
    <Input
      label="Núm.tabs"
      id="numTabs"
      name="numTabs"
      :value="String(numTabs)"
      :onChange="handleNumTabChange"
      :errorMessage="numTabsErrorMessage"
    />
    <hr />

    <template v-for="(tab, index) in state.formTabs">
      <Input
        label="Título"
        id="title"
        name="title"
        :value="tab.title"
        :onChange="(event) => changeTabField('title', index, (event?.target as any)?.value)"
        :errorMessage="tab.errorMessage?.title"
      />

      <TextArea
        label="Conteúdo"
        id="content"
        name="content"
        :value="tab.content"
        :onChange="(event) => changeTabField('content', index, (event?.target as any)?.value)"
        :errorMessage="tab.errorMessage?.content"
      ></TextArea>
    </template>

    <Button text="Salvar" :action="saveFormTabs"></Button>
  </Box>
</template>

<script setup lang="ts">
import { inject, reactive, ref, watch } from "vue";

import Box from "../Box/Box.vue";
import Button from "../Button/Button.vue";
import Input from "../Input/Input.vue";
import TextArea from "../TextArea/TextArea.vue";
import { generateTabs, validateTabs } from "../../utils";

export type FormTab = {
  title: string;
  content: string;
  errorMessage: {
    title?: string;
    content?: string;
  };
};

let numTabs = ref(0);
let numTabsErrorMessage = ref("");
const state = reactive({
  formTabs: generateTabs(numTabs.value),
});

const { setTabs } = inject("actions") as any;

function saveFormTabs() {
  const { validatedTabs, hasErrors } = validateTabs(state.formTabs);

  if (hasErrors) {
    state.formTabs = validatedTabs;
    return;
  }

  setTabs(state.formTabs);
}

function changeTabField(
  field: "title" | "content",
  index: number,
  value: string
) {
  state.formTabs = state.formTabs.map((tab, i) => {
    if (index === i) {
      return {
        ...tab,
        [field]: value,
      };
    }
    return tab;
  });
}

function handleNumTabChange(event: Event) {
  numTabs.value = Number((event?.target as any)?.value);
}

watch(numTabs, () => {
  if (numTabs.value < 1) {
    numTabsErrorMessage.value = "Não pode ser menor do que 1";
    return;
  }

  state.formTabs = generateTabs(numTabs.value, state.formTabs);
  numTabsErrorMessage.value = "";
});
</script>

// tab_2_angular/src/app/components/Form/form.component.ts
export type FormTab = {
  title: string;
  content: string;
  errorMessage: {
    title?: string;
    content?: string;
  };
};

import { Component, Input, OnInit } from '@angular/core';
import { Store, select } from '@ngrx/store';
import { generateTabs, validateTabs } from 'src/utils';
import { setTabs } from '../../store/ngrx';

@Component({
  selector: 'app-tabs-form',
  template: `
    <app-box title="Tabs">
      <app-input
        label="Núm.tabs"
        id="numTabs"
        name="numTabs"
        [value]="numTabs.toString()"
        (change)="handleNumTabChange($event)"
        [errorMessage]="numTabsErrorMessage"
      ></app-input>
      <hr />

      <div *ngFor="let tab of formTabs; let i = index">
        <app-input
          label="Título"
          id="title"
          name="title"
          [value]="tab.title"
          (change)="changeTabField('title', i, $event)"
          [errorMessage]="tab.errorMessage?.title"
        ></app-input>

        <app-text-area
          label="Conteúdo"
          id="content"
          name="content"
          [value]="tab.content"
          (change)="changeTabField('content', i, $event)"
          [errorMessage]="tab.errorMessage?.content"
        ></app-text-area>
      </div>

      <app-button text="Salvar" (action)="saveFormTabs()"></app-button>
    </app-box>
  `,
  styles: [
    `
      .TabNavList {
        display: flex;
      }
    `,
  ],
})
export class FormComponent {
  numTabs = 0;
  numTabsErrorMessage = '';
  formTabs: FormTab[] = [];

  constructor(public store: Store<any>) {}

  saveFormTabs() {
    const { validatedTabs, hasErrors } = validateTabs(this.formTabs);

    if (hasErrors) {
      this.formTabs = validatedTabs;
      return;
    }

    this.store.dispatch(
      setTabs({
        tabs: this.formTabs,
      })
    );
  }

  changeTabField(field: 'title' | 'content', index: number, event: Event) {
    this.formTabs = this.formTabs.map((tab, i) => {
      if (index === i) {
        return {
          ...tab,
          [field]: (event?.target as any)?.value,
        };
      }
      return tab;
    });
  }

  handleNumTabChange(event: Event) {
    this.numTabs = Number((event?.target as any)?.value);

    if (this.numTabs < 1) {
      this.numTabsErrorMessage = 'Não pode ser menor do que 1';
      return;
    }

    this.formTabs = generateTabs(this.numTabs, this.formTabs);
    this.numTabsErrorMessage = '';
  }
}
