// quiz/src/components/task/TabContent.vue
<template>
  <p class="TabContent">{{ content || DEFAULT_CONTENT }}</p>
</template>

<script setup lang="ts">
const props = defineProps<{
  content?: string;
}>();

const DEFAULT_CONTENT = "Selecione uma tab...";
</script>

<style scoped>
.TabContent {
  background: #f0f0f0;
  border: 1px solid #aaaaaa;
  box-sizing: border-box;
  border-radius: 10px;
  min-height: 130px;
  padding: 24px;

  font-style: normal;
  font-weight: 400;
  font-size: 20px;
  line-height: 24px;
}
</style>

// tab_2_svelte/src/components/Tabs/TabContent.svelte
<template>
  <p class="TabContent">{ selectedTab?.content }</p>
</template>

<script lang="ts">
import type { AppContextType } from "src/utils";
import { getContext } from "svelte";

const {tabs, selectedTabIndex} = getContext<AppContextType>('appContext')

$: selectedTab = $tabs.filter(
  (_, index) => index === $selectedTabIndex
)?.[0];

</script>

<style>
  .TabContent {
  box-sizing: border-box;
  border-radius: 10px;
  min-height: 130px;
  padding: 0 24px;

  font-style: normal;
  font-weight: 400;
  font-size: 14px;
  line-height: 24px;
}
</style>
