// tab_2_vue/src/components/TextArea/TextArea.vue
<template>
  <div class="TextAreaContainer">
    <label :for="id">{{ label }}</label>
    <textarea
      :id="id"
      :name="name"
      :value="value"
      @input="onChange($event)"
    ></textarea>
    <span v-if="!!errorMessage" class="errorMessage">{{ errorMessage }}</span>
  </div>
</template>

<script setup lang="ts">
defineProps<{
  id: string;
  name: string;
  label: HTMLElement | string;
  errorMessage?: string;
  value?: string;
  onChange: (payload: Event) => void;
}>();
</script>

<style>
.TextAreaContainer span {
  display: block;
  color: red;
  font-size: 12px;
}
</style>

// tab_2_react/src/components/TextArea/TextArea.component.tsx
import "./TextArea.styles.css";

type TextAreaProps = {
  id: string;
  name: string;
  label: React.ReactNode;
  errorMessage?: string;
  value?: string;
  onChange: React.ChangeEventHandler<HTMLTextAreaElement> | undefined;
};

export function TextArea({
  id,
  name,
  label,
  errorMessage,
  value,
  onChange,
}: TextAreaProps) {
  return (
    <div className="TextAreaContainer">
      <label htmlFor={id}>{label}</label>
      <textarea id={id} name={name} value={value} onChange={onChange} />
      {errorMessage && <span className="errorMessage">{errorMessage}</span>}
    </div>
  );
}
