// tab_2_vue/src/components/Button/Button.vue
<template>
  <button :class="'Button'" @click="action" type="button">
    {{ text }}
  </button>
</template>

<script setup lang="ts">
defineProps<{
  text?: string;
  action?: () => void;
}>();
</script>

<style>
.Button {
  padding: 8px;
  background: #7b61ff;
  color: white;
  border: none;
}
</style>

// tab_2_svelte/src/components/Button/Button.svelte
<template>
  <button class={'Button'} on:click={onClick} type="button">
    {text}
  </button>
</template>

<script lang="ts">
  import { createEventDispatcher } from "svelte"

  export let text: string

  const dispatcher = createEventDispatcher<{action: string}>()

function onClick() {
	dispatcher('action')
}
</script>

<style>
.Button {
  padding: 8px;
  background: #7b61ff;
  color: white;
  border: none;
}
</style>
