// tab_2_svelte/src/components/AppProvider/AppProvider.svelte
<template>
  <slot></slot>
</template>

<script lang="ts">
import { writable, get, Writable } from "svelte/store";
import { setContext } from "svelte";
import type { Tab } from "src/utils";

const initialTabsValue: Tab[] = [
  {
    content: "Sem Conteúdo",
    title: "Tab",
  },
];

const tabs = writable(initialTabsValue);
const selectedTabIndex = writable(0);

function onTabChange(index: number) {
  selectedTabIndex.set(index);
}

function setTabs(newTabs: Tab[]) {
  console.log('setTabs', newTabs)
  tabs.set(newTabs);
}

setContext("appContext", {
  tabs,
  selectedTabIndex,
  onTabChange,
  setTabs,
});

tabs.subscribe(() => {
  selectedTabIndex.set(0);
});
</script>

// tab_2_vue/src/components/AppProvider/AppProvider.vue
<template>
  <slot></slot>
</template>

<script setup lang="ts">
import { provide, reactive, computed, watch, ref } from "vue";

export type Tab = {
  title: string;
  content: string;
};

const initialTabsValue: Tab[] = [
  {
    content: "Sem Conteúdo",
    title: "Tab",
  },
];

const state = reactive({
  tabs: initialTabsValue,
  selectedTabIndex: 0,
});

const selectedTab = computed(
  () => state.tabs.filter((_, index) => index === state.selectedTabIndex)?.[0]
);

function onTabChange(index: number) {
  state.selectedTabIndex = index;
}

function setTabs(newTabs: Tab[]) {
  state.tabs = newTabs;
}

provide("state", {
  tabs: computed(() => state.tabs),
  selectedTabIndex: computed(() => state.selectedTabIndex),
  selectedTab,
});
provide("actions", {
  onTabChange,
  setTabs,
});

watch(
  () => state.tabs,
  () => {
    state.selectedTabIndex = 0;
  }
);
</script>

<style></style>
