// tab_2_svelte/src/App.svelte
<template>
  <AppProvider>
  <div class="App">
    <TabsForm />

    <Box title="Conteúdo" className="BoxContent">
      <Tabs />
    </Box>
  </div>
  </AppProvider>
</template>

<script lang="ts">
import Box from "./components/Box/Box.svelte";
import Tabs from "./components/Tabs/index.svelte";
import AppProvider from "./components/AppProvider/AppProvider.svelte";
import TabsForm from "./components/Form/Form.svelte";
</script>

<style>
@import "./App.css";
</style>

// tab_2_react/src/App.tsx
import { Box } from "./components/Box/Box.component";
import "./App.css";
import { Tabs } from "./components/Tabs";
import { TabsForm } from "./Form.component";
import { TabProvider } from "./context/TabContext";

function App() {
  return (
    <TabProvider>
      <div className="App">
        <TabsForm />

        <Box title="Conteúdo" className="BoxContent">
          <Tabs />
        </Box>
      </div>
    </TabProvider>
  );
}

export default App;
