// quiz/src/components/task/Container.vue
<template>
  <div class="Container">
    <div class="TabList">
      <TabHeader
        v-for="(tab, index) in tabs"
        :key="index"
        :title="tab.title"
        :selected="state?.selectedTab?.title === tab.title"
        @onSelect="select"
      />
    </div>
    <TabContent :content="state?.selectedTab?.content" />
  </div>
</template>

<script setup lang="ts">
import { reactive, ref, computed } from "vue";
import TabContent from "./TabContent.vue";
import TabHeader from "./TabHeader.vue";

type Tab = {
  title: string;
  content: string;
};

const tabs: Tab[] = [
  {
    title: "tab 1",
    content: "Conteúdo da tab 1",
  },
  {
    title: "tab 2",
    content: "Conteúdo da tab 2",
  },
  {
    title: "tab 3",
    content: "Conteúdo da tab 3",
  },
  {
    title: "tab 4",
    content: "Conteúdo da tab 4",
  },
];

const state = reactive({
  selectedTab: {},
});

function select(title: string) {
  const newSelectedTab = tabs.find((tab) => title === tab.title) || {};
  state.selectedTab = newSelectedTab;
}
</script>

<style scoped>
.Container {
  max-width: 514px;
  min-width: 430px;
  width: 100%;

  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}

.TabList {
  display: flex;
  justify-content: space-between;
}
</style>

// quiz/src/components/Container.svelte
<script lang="ts">
import TabHeader from './TabHeader.svelte'
import TabContent from './TabContent.svelte'

type Tab = {
  title: string;
  content: string;
};

  const tabs: Tab[] = [
    {
      title: "tab 1",
      content: "Conteúdo da tab 1"
    },
    {
      title: "tab 2",
      content: "Conteúdo da tab 2"
    },
    {
      title: "tab 3",
      content: "Conteúdo da tab 3"
    },
    {
      title: "tab 4",
      content: "Conteúdo da tab 4"
    }
  ];

  let selectedTab: Tab;

  function select(event: CustomEvent<string>) {
    const title = event.detail
    const newSelectedTab = tabs.find((tab) => title === tab.title);
    selectedTab = newSelectedTab;
  }
</script>



<main class="Container">
      <div class="TabList">
        	{#each tabs as tab (tab.title)}
          <TabHeader
            title={tab.title}
            selected={selectedTab?.title === tab.title}
            on:selection={e => select(e)}
          ></TabHeader>
          {/each}
        </div>
      <TabContent content={selectedTab?.content}> </TabContent>
    </main>

    <style>
      .Container {
        max-width: 514px;
        min-width: 430px;
        width: 100%;
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
      }
      .TabList {
        display: flex;
        justify-content: space-between;
      }
    </style>
