// tab_2_angular/src/app/components/Tabs/tab-content.component.ts
import { Component } from '@angular/core';
import { Store } from '@ngrx/store';

@Component({
  selector: 'app-tab-content',
  template: `
    <p class="TabContent">
      {{ (state$ | async).selectedTab?.content }}
    </p>
  `,
  styles: [
    `
      .TabContent {
        box-sizing: border-box;
        border-radius: 10px;
        min-height: 130px;
        padding: 0 24px;

        font-style: normal;
        font-weight: 400;
        font-size: 14px;
        line-height: 24px;
      }
    `,
  ],
})
export class TabContentComponent {
  state$ = this.store.select('AppReducer');

  constructor(public store: Store<any>) {}
}

// quiz/src/components/TabContent.svelte
<script lang="ts">
  export let content: string = "Selecione uma tab...";
</script>

    <p class="TabContent">{content}</p>

<style>
      .TabContent {
        background: #f0f0f0;
        border: 1px solid #aaaaaa;
        box-sizing: border-box;
        border-radius: 10px;
        min-height: 130px;
        padding: 24px;
        font-style: normal;
        font-weight: 400;
        font-size: 20px;
        line-height: 24px;
      }
</style>
