// quiz/src/components/task/TabHeader.vue
<template>
  <button type="button" :class="customClass" @click="select(title)">
    {{ title }}
  </button>
</template>

<script setup lang="ts">
import { reactive, ref, computed } from "vue";
const props =
  defineProps<{
    title?: string;
    selected?: boolean;
    variant?: "contained" | "outlined";
  }>();

const customClass = computed(
  () =>
    `TabHeader ${props.selected ? "selected" : ""} ${
      props.variant || "contained"
    }`
);

const emit =
  defineEmits<{
    onSelect: (title: string) => void;
  }>();

function select(title?: string) {
  emit("onSelect", title);
}
</script>

<style scoped>
.TabHeader {
  background: #cccccc;
  border: 1px solid #777777;
  box-sizing: border-box;
  border-radius: 3px;
  padding: 4px 24px;

  font-style: normal;
  font-weight: 400;
  font-size: 16px;
  line-height: 19px;
  display: flex;
  align-items: center;
  text-align: center;
  cursor: pointer;
}
.TabHeader.selected {
  background: #aaaaaa;
  font-weight: 700;
}

.TabHeader.outlined {
  background: transparent;
  border: 1px solid #777777;
}

.TabHeader.outlined.selected {
  background: transparent;
  border-width: 2px;
}
</style>

// quiz/src/components/TabHeader.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte"

  export let title: string;
  export let selected: boolean;
  export let variant: 'contained' | 'outlined' = "contained";

const dispatcher = createEventDispatcher<{selection: string}>()

function onClick() {
	dispatcher('selection', title)
}
</script>

    <button
      type="button"
      class={`TabHeader ${variant}`}
      class:selected={selected}
      on:click={onClick}
    >
      { title }
    </button>

<style>
      .TabHeader {
        background: #cccccc;
        border: 1px solid #777777;
        box-sizing: border-box;
        border-radius: 3px;
        padding: 4px 24px;
        font-style: normal;
        font-weight: 400;
        font-size: 16px;
        line-height: 19px;
        display: flex;
        align-items: center;
        text-align: center;
        cursor: pointer;
      }
      .TabHeader.selected {
        background: #aaaaaa;
        font-weight: 700;
      }

      .TabHeader.outlined {
  background: transparent;
  border: 1px solid #777777;
}

.TabHeader.outlined.selected {
  background: transparent;
  border-width: 2px;
}
</style>
