// tab_2_svelte/src/components/Tabs/index.svelte
<template>
  <div class="Tabs">
    <div>
      <div class="TabNavList">
        {#each $tabs as tab, index (index)}
          <TabHeader
            index={index}
            title={tab.title}
          />
        {/each}
      </div>
      <TabContent />
    </div>
  </div>
</template>

<script lang="ts">
import type { AppContextType } from "src/utils";

import { getContext } from "svelte";

import TabContent from "./TabContent.svelte";
import TabHeader from "./TabHeader.svelte";

const { tabs } = getContext<AppContextType>('appContext')
</script>

<style>
.TabNavList {
  display: flex;
}
</style>

// tab_2_react/src/components/Tabs/index.tsx
import { useTabContext } from "../../context/TabContext";
import { TabContent } from "./TabContent.component";
import { TabHeader } from "./TabHeader.component";
import "./Tabs.styles.css";

export function Tabs() {
  const { tabs } = useTabContext();

  return (
    <div className="Tabs">
      <div>
        <div className="TabNavList">
          {tabs?.map((tab, index) => (
            <TabHeader index={index} title={tab.title} />
          ))}
        </div>

        <TabContent />
      </div>
    </div>
  );
}
