// tab_2_vue/src/components/Tabs/TabHeader.vue
<template>
  <div>
    <button :class="className" type="button" @click="handleOnClick">
      {{ title }}
    </button>
  </div>
</template>

<script setup lang="ts">
import { inject, computed } from "vue";

const { title, index } = defineProps<{
  title: string;
  index: number;
}>();

const { selectedTabIndex } = inject("state") as any;
const { onTabChange } = inject("actions") as any;

const className = computed(
  () => `TabHeader ${selectedTabIndex.value === index ? "selected" : ""}`
);

function handleOnClick() {
  onTabChange(index);
}
</script>

<style>
.InputContainer span {
  display: block;
  color: red;
  font-size: 12px;
}
</style>

// tab_2_react/src/components/Tabs/TabHeader.component.tsx
import { useTabContext } from "../../context/TabContext";

type TabHeaderProps = {
  title: string;
  index: number;
};

export function TabHeader({ title, index }: TabHeaderProps) {
  const { selectedTabIndex, onTabChange } = useTabContext();
  const selected = selectedTabIndex === index;

  const classNames = `TabHeader ${selected ? "selected" : ""}`;

  return (
    <div>
      <button
        className={classNames}
        type="button"
        onClick={() => onTabChange(index)}
      >
        {title}
      </button>
    </div>
  );
}
