// tab_2_svelte/src/components/Input/Input.svelte
<template>
  <div class="InputContainer">
    <label for={id}>{label}</label>
    <input id={id} name={name} value={value} on:input={onChange} />
    {#if !!errorMessage}
      <span class="errorMessage">
        {errorMessage}
      </span>
    {/if}
  </div>
</template>

<script lang="ts">
  import { createEventDispatcher } from "svelte"

  export let id: string;
  export let name: string;
  export let label: HTMLElement | string; // 
  export let errorMessage: string;
  export let value: string;


  const dispatcher = createEventDispatcher<{Change: any}>()

  const onChange = (event) => {
    dispatcher('Change', event.target.value)
  }
</script>

<style>
.InputContainer span {
  display: block;
  color: red;
  font-size: 12px;
}
</style>

// tab_2_angular/src/app/components/Input/input.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-input',
  template: `
    <div class="InputContainer">
      <label [for]="id">{{ label }}</label>
      <input
        [id]="id"
        [name]="name"
        [value]="value"
        (input)="change.emit($event)"
      />
      <span *ngIf="!!errorMessage" class="errorMessage">{{
        errorMessage
      }}</span>
    </div>
  `,
  styles: [
    `
      .InputContainer span {
        display: block;
        color: red;
        font-size: 12px;
      }
    `,
  ],
})
export class InputComponent {
  @Input() id?: string;
  @Input() name?: string;
  @Input() label?: HTMLElement | string;
  @Input() errorMessage?: string;
  @Input() value?: string;

  @Output() change = new EventEmitter();

  constructor() {}
}
