// tab_2_vue/src/components/Input/Input.vue
<template>
  <div className="InputContainer">
    <label :for="id">{{ label }}</label>
    <input :id="id" :name="name" :value="value" @input="onChange($event)" />
    <span v-if="!!errorMessage" className="errorMessage">{{
      errorMessage
    }}</span>
  </div>
</template>

<script setup lang="ts">
defineProps<{
  id: string;
  name: string;
  label: HTMLElement | string; // any
  errorMessage?: string;
  value?: string;
  onChange: (payload: Event) => void;
}>();
</script>

<style>
.InputContainer span {
  display: block;
  color: red;
  font-size: 12px;
}
</style>

// tab_2_react/src/components/Input/Input.component.tsx
import "./Input.styles.css";

type InputProps = {
  id: string;
  name: string;
  label: React.ReactNode;
  errorMessage?: string;
  value?: string;
  onChange: React.ChangeEventHandler<HTMLInputElement> | undefined;
};

export function Input({
  id,
  name,
  label,
  errorMessage,
  value,
  onChange,
}: InputProps) {
  return (
    <div className="InputContainer">
      <label htmlFor={id}>{label}</label>
      <input id={id} name={name} value={value} onChange={onChange} />
      {errorMessage && <span className="errorMessage">{errorMessage}</span>}
    </div>
  );
}
