// tab_2_angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'tab_2_angular';
}

<div class="App">
  <app-tabs-form></app-tabs-form>

  <app-box title="Conteúdo">
    <app-tabs #children></app-tabs>
  </app-box>
</div>

// tab_2_svelte/src/App.svelte
<template>
  <AppProvider>
  <div class="App">
    <TabsForm />

    <Box title="Conteúdo" className="BoxContent">
      <Tabs />
    </Box>
  </div>
  </AppProvider>
</template>

<script lang="ts">
import Box from "./components/Box/Box.svelte";
import Tabs from "./components/Tabs/index.svelte";
import AppProvider from "./components/AppProvider/AppProvider.svelte";
import TabsForm from "./components/Form/Form.svelte";
</script>

<style>
@import "./App.css";
</style>
