// tab_2_svelte/src/components/Input/Input.svelte
<template>
  <div class="InputContainer">
    <label for={id}>{label}</label>
    <input id={id} name={name} value={value} on:input={onChange} />
    {#if !!errorMessage}
      <span class="errorMessage">
        {errorMessage}
      </span>
    {/if}
  </div>
</template>

<script lang="ts">
  import { createEventDispatcher } from "svelte"

  export let id: string;
  export let name: string;
  export let label: HTMLElement | string; // 
  export let errorMessage: string;
  export let value: string;


  const dispatcher = createEventDispatcher<{Change: any}>()

  const onChange = (event) => {
    dispatcher('Change', event.target.value)
  }
</script>

<style>
.InputContainer span {
  display: block;
  color: red;
  font-size: 12px;
}
</style>

// tab_2_vue/src/components/Input/Input.vue
<template>
  <div className="InputContainer">
    <label :for="id">{{ label }}</label>
    <input :id="id" :name="name" :value="value" @input="onChange($event)" />
    <span v-if="!!errorMessage" className="errorMessage">{{
      errorMessage
    }}</span>
  </div>
</template>

<script setup lang="ts">
defineProps<{
  id: string;
  name: string;
  label: HTMLElement | string; // any
  errorMessage?: string;
  value?: string;
  onChange: (payload: Event) => void;
}>();
</script>

<style>
.InputContainer span {
  display: block;
  color: red;
  font-size: 12px;
}
</style>
