// tab_2_vue/src/components/Button/Button.vue
<template>
  <button :class="'Button'" @click="action" type="button">
    {{ text }}
  </button>
</template>

<script setup lang="ts">
defineProps<{
  text?: string;
  action?: () => void;
}>();
</script>

<style>
.Button {
  padding: 8px;
  background: #7b61ff;
  color: white;
  border: none;
}
</style>

// tab_2_angular/src/app/components/Button/button.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-button',
  template: `
    <button class="Button" (click)="action?.emit()" type="button">
      {{ text }}
    </button>
  `,
  styles: [
    `
      .Button {
        padding: 8px;
        background: #7b61ff;
        color: white;
        border: none;
      }
    `,
  ],
})
export class ButtonComponent {
  @Input() text?: string;
  @Output() action = new EventEmitter();

  constructor() {}
}
