// tab_2_svelte/src/components/TextArea/TextArea.svelte
<template>
  <div class="TextAreaContainer">
    <label for={id}>{label}</label>
    <textarea id={id} name={name} value={value} on:input={onChange} />
    {#if !!errorMessage}
      <span class="errorMessage">
        {errorMessage}
      </span>
    {/if}
  </div>
</template>

<script lang="ts">
  import { createEventDispatcher } from "svelte"

  export let id: string;
  export let name: string;
  export let label: HTMLElement | string; // 
  export let errorMessage: string;
  export let value: string;


  const dispatcher = createEventDispatcher<{Change: any}>()

  const onChange = (event) => {
    dispatcher('Change', event.target.value)
  }
</script>

<style>
.TextAreaContainer span {
  display: block;
  color: red;
  font-size: 12px;
}
</style>

// tab_2_angular/src/app/components/TextArea/text-area.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

type Tab = {
  title: string;
  content: string;
  variant?: 'contained' | 'outlined';
};

@Component({
  selector: 'app-text-area',
  template: `
    <div class="TextAreaContainer">
      <label [for]="id">{{ label }}</label>
      <textarea
        [id]="id"
        [name]="name"
        [value]="value"
        (input)="change.emit($event)"
      ></textarea>
      <span *ngIf="!!errorMessage" class="errorMessage">{{
        errorMessage
      }}</span>
    </div>
  `,
  styles: [
    `
      .TextAreaContainer span {
        display: block;
        color: red;
        font-size: 12px;
      }
    `,
  ],
})
export class TextAreaComponent {
  @Input() id?: string;
  @Input() name?: string;
  @Input() label?: HTMLElement | string;
  @Input() errorMessage?: string;
  @Input() value?: string;
  @Output() change = new EventEmitter();

  constructor() {}
}
